/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-111025-g65a1e8ee2c-20230606"
#endif /* AVUTIL_FFVERSION_H */
